//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Age = &struct {
	Child   postgres.StringExpression
	Adult   postgres.StringExpression
	Elderly postgres.StringExpression
}{
	Child:   postgres.NewEnumValue("child"),
	Adult:   postgres.NewEnumValue("adult"),
	Elderly: postgres.NewEnumValue("elderly"),
}
