//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Ethnicity = &struct {
	Light  postgres.StringExpression
	Medium postgres.StringExpression
	Dark   postgres.StringExpression
	Other  postgres.StringExpression
}{
	Light:  postgres.NewEnumValue("light"),
	Medium: postgres.NewEnumValue("medium"),
	Dark:   postgres.NewEnumValue("dark"),
	Other:  postgres.NewEnumValue("other"),
}
