//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var GeneratedPackageStatus = &struct {
	Created    postgres.StringExpression
	Processing postgres.StringExpression
	Generated  postgres.StringExpression
}{
	Created:    postgres.NewEnumValue("created"),
	Processing: postgres.NewEnumValue("processing"),
	Generated:  postgres.NewEnumValue("generated"),
}
