//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var HairColor = &struct {
	Black  postgres.StringExpression
	Brown  postgres.StringExpression
	Blond  postgres.StringExpression
	Gray   postgres.StringExpression
	Red    postgres.StringExpression
	Nohair postgres.StringExpression
	Other  postgres.StringExpression
}{
	Black:  postgres.NewEnumValue("black"),
	Brown:  postgres.NewEnumValue("brown"),
	Blond:  postgres.NewEnumValue("blond"),
	Gray:   postgres.NewEnumValue("gray"),
	Red:    postgres.NewEnumValue("red"),
	Nohair: postgres.NewEnumValue("nohair"),
	Other:  postgres.NewEnumValue("other"),
}
