//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var OrderStatus = &struct {
	Created   postgres.StringExpression
	Pending   postgres.StringExpression
	Paid      postgres.StringExpression
	Cancelled postgres.StringExpression
	Refunded  postgres.StringExpression
}{
	Created:   postgres.NewEnumValue("created"),
	Pending:   postgres.NewEnumValue("pending"),
	Paid:      postgres.NewEnumValue("paid"),
	Cancelled: postgres.NewEnumValue("cancelled"),
	Refunded:  postgres.NewEnumValue("refunded"),
}
