//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var AalLevel = &struct {
	Aal1 postgres.StringExpression
	Aal2 postgres.StringExpression
	Aal3 postgres.StringExpression
}{
	Aal1: postgres.NewEnumValue("aal1"),
	Aal2: postgres.NewEnumValue("aal2"),
	Aal3: postgres.NewEnumValue("aal3"),
}
