//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Character = Character.FromSchema(schema)
	CharacterImg = CharacterImg.FromSchema(schema)
	CharacterModel = CharacterModel.FromSchema(schema)
	Coupon = Coupon.FromSchema(schema)
	GeneratedPackage = GeneratedPackage.FromSchema(schema)
	GeneratedPackageImg = GeneratedPackageImg.FromSchema(schema)
	Package = Package.FromSchema(schema)
	PackageExampleImg = PackageExampleImg.FromSchema(schema)
	PackageOrder = PackageOrder.FromSchema(schema)
	PackageOrderItem = PackageOrderItem.FromSchema(schema)
	PackagePrice = PackagePrice.FromSchema(schema)
	SchemaMigrations = SchemaMigrations.FromSchema(schema)
}
