//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type AalLevel string

const (
	AalLevel_Aal1 AalLevel = "aal1"
	AalLevel_Aal2 AalLevel = "aal2"
	AalLevel_Aal3 AalLevel = "aal3"
)

func (e *AalLevel) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "aal1":
		*e = AalLevel_Aal1
	case "aal2":
		*e = AalLevel_Aal2
	case "aal3":
		*e = AalLevel_Aal3
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for AalLevel enum")
	}

	return nil
}

func (e AalLevel) String() string {
	return string(e)
}
