//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type AuditLogEntries struct {
	InstanceID *uuid.UUID
	ID         uuid.UUID `sql:"primary_key"`
	Payload    *string
	CreatedAt  *time.Time
	IPAddress  string
}
