//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type CodeChallengeMethod string

const (
	CodeChallengeMethod_S256  CodeChallengeMethod = "s256"
	CodeChallengeMethod_Plain CodeChallengeMethod = "plain"
)

func (e *CodeChallengeMethod) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "s256":
		*e = CodeChallengeMethod_S256
	case "plain":
		*e = CodeChallengeMethod_Plain
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for CodeChallengeMethod enum")
	}

	return nil
}

func (e CodeChallengeMethod) String() string {
	return string(e)
}
