//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type FactorStatus string

const (
	FactorStatus_Unverified FactorStatus = "unverified"
	FactorStatus_Verified   FactorStatus = "verified"
)

func (e *FactorStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "unverified":
		*e = FactorStatus_Unverified
	case "verified":
		*e = FactorStatus_Verified
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for FactorStatus enum")
	}

	return nil
}

func (e FactorStatus) String() string {
	return string(e)
}
