//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type FlowState struct {
	ID                   uuid.UUID `sql:"primary_key"`
	UserID               *uuid.UUID
	AuthCode             string
	CodeChallengeMethod  CodeChallengeMethod
	CodeChallenge        string
	ProviderType         string
	ProviderAccessToken  *string
	ProviderRefreshToken *string
	CreatedAt            *time.Time
	UpdatedAt            *time.Time
	AuthenticationMethod string
}
