//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Identities struct {
	ProviderID   string
	UserID       uuid.UUID
	IdentityData string
	Provider     string
	LastSignInAt *time.Time
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	Email        *string
	ID           uuid.UUID `sql:"primary_key"`
}
