//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type RefreshTokens struct {
	InstanceID *uuid.UUID
	ID         int64 `sql:"primary_key"`
	Token      *string
	UserID     *string
	Revoked    *bool
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
	Parent     *string
	SessionID  *uuid.UUID
}
