//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type SamlProviders struct {
	ID               uuid.UUID `sql:"primary_key"`
	SsoProviderID    uuid.UUID
	EntityID         string
	MetadataXML      string
	MetadataURL      *string
	AttributeMapping *string
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
}
