//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Users struct {
	InstanceID               *uuid.UUID
	ID                       uuid.UUID `sql:"primary_key"`
	Aud                      *string
	Role                     *string
	Email                    *string
	EncryptedPassword        *string
	EmailConfirmedAt         *time.Time
	InvitedAt                *time.Time
	ConfirmationToken        *string
	ConfirmationSentAt       *time.Time
	RecoveryToken            *string
	RecoverySentAt           *time.Time
	EmailChangeTokenNew      *string
	EmailChange              *string
	EmailChangeSentAt        *time.Time
	LastSignInAt             *time.Time
	RawAppMetaData           *string
	RawUserMetaData          *string
	IsSuperAdmin             *bool
	CreatedAt                *time.Time
	UpdatedAt                *time.Time
	Phone                    *string
	PhoneConfirmedAt         *time.Time
	PhoneChange              *string
	PhoneChangeToken         *string
	PhoneChangeSentAt        *time.Time
	ConfirmedAt              *time.Time
	EmailChangeTokenCurrent  *string
	EmailChangeConfirmStatus *int16
	BannedUntil              *time.Time
	ReauthenticationToken    *string
	ReauthenticationSentAt   *time.Time
	IsSsoUser                bool
	DeletedAt                *time.Time
}
