//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Character struct {
	ID        int32 `sql:"primary_key"`
	UserID    uuid.UUID
	Name      string
	Gender    Gender
	HairColor HairColor
	EyeColor  EyeColor
	Ethnicity Ethnicity
	Age       Age
	Created   time.Time
}
