//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Ethnicity string

const (
	Ethnicity_Light  Ethnicity = "light"
	Ethnicity_Medium Ethnicity = "medium"
	Ethnicity_Dark   Ethnicity = "dark"
	Ethnicity_Other  Ethnicity = "other"
)

func (e *Ethnicity) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "light":
		*e = Ethnicity_Light
	case "medium":
		*e = Ethnicity_Medium
	case "dark":
		*e = Ethnicity_Dark
	case "other":
		*e = Ethnicity_Other
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Ethnicity enum")
	}

	return nil
}

func (e Ethnicity) String() string {
	return string(e)
}
