//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type GeneratedPackageStatus string

const (
	GeneratedPackageStatus_Created    GeneratedPackageStatus = "created"
	GeneratedPackageStatus_Processing GeneratedPackageStatus = "processing"
	GeneratedPackageStatus_Generated  GeneratedPackageStatus = "generated"
)

func (e *GeneratedPackageStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "created":
		*e = GeneratedPackageStatus_Created
	case "processing":
		*e = GeneratedPackageStatus_Processing
	case "generated":
		*e = GeneratedPackageStatus_Generated
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for GeneratedPackageStatus enum")
	}

	return nil
}

func (e GeneratedPackageStatus) String() string {
	return string(e)
}
