//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type GeneratedPackage struct {
	ID                 int32 `sql:"primary_key"`
	PackageOrderItemID int32
	CharacterID        int32
	CoverImgURL        string
	Created            time.Time
}
