//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type PackageOrder struct {
	ID                      int32 `sql:"primary_key"`
	UserID                  uuid.UUID
	Created                 time.Time
	TotalAmount             int32
	Currency                string
	Status                  OrderStatus
	CouponID                *int32
	StripePaymentIntentID   *string
	StripeCheckoutSessionID *string
}
